define("SHARED/portalRequest",["SHARED/jquery","SHARED/uiMaskLayer","SHARED/I18NMessage","SHARED/base"],function(i,g,a,b){eXo.define.names=["$","uiMaskLayer","msg","base"];eXo.define.deps=[i,g,a,b];return function(b,a,c,d){function k(a){a=b(a).children("div");this.portletId=a[0].innerHTML;this.portletData=a[1].innerHTML;this.blocksToUpdate=null;var c=b(a[1]).children(".BlockToUpdate");if(0<c.length){var d=this.blocksToUpdate=[];c.each(function(){var a=b(this).children("div");d[d.length]={blockId:a[0].innerHTML,
data:a[1]};d[d.length-1].scripts=b(a[1]).find("script")})}else this.scripts=b(a[1]).find("script")}function n(a){var c=document.createElement("div");c.innerHTML=a;var a=b(c).children().first(),d=this;d.portletResponses=[];a.children("div.PortletResponse").each(function(){d.portletResponses[d.portletResponses.length]=new k(this)});a.children("div.PortalResponseData").each(function(){d.data=this;d.blocksToUpdate=[];b(this).children(".BlockToUpdate").each(function(){var a=b(this).children("div"),c=d.blocksToUpdate.length;
d.blocksToUpdate[c]={blockId:a[0].innerHTML,data:a[1]};d.blocksToUpdate[c].scripts=b(a[1]).find("script")})});a.children("div.MarkupHeadElements").each(function(){d.markupHeadElements=new g(this)});a.children("div.LoadingScripts").each(function(){d.loadingScripts=new i(this)});a.children("div.PortalResponseScript").each(function(){d.script=this.innerHTML;b(this).css("display","none")})}function g(a){a=b(a);this.titles=a.find("title");this.bases=a.find("base");this.links=a.find("link");this.metas=
a.find("meta");this.scripts=a.find("script");this.styles=a.find("style");for(a=0;a<this.scripts.length;a++){var c=this.scripts,d=a,f=this.scripts[a],e=document.createElement("script");e.type="text/javascript";e.className=f.className;if(f.defer)e.defer=f.defer;f.src?e.src=f.src:e.text=f.innerHTML;c[d]=e}}function i(a){this.immediateScripts=[];for(var a=b(a).children(".ImmediateScripts").first().html(),a=a.replace(/^\s*/,"").split(","),c=0;c<a.length;c++)""!==a[c]&&this.immediateScripts.push(a[c])}
function j(a,c){var d=b("head");d.find("#"+a).remove();var f=b(c);f.attr("id",a);d[0].appendChild(f[0])}function p(a,c,d){var f={request:null,timeout:8E4,aborted:!1};f.method=null!=a?a:"GET";f.url=null!=c?c:window.location.href;f.queryString=null!=d?d:null;f.responseReceived=!1;f.status=null;f.statusText=null;f.responseText=null;f.responseXML=null;f.onTimeout=null;f.onLoading=null;f.onComplete=null;f.onSuccess=null;f.callBack=null;f.onError=null;f.isAsynchronize=function(){var a=!1,b;b="ajax_async".replace(/[\[]/,
"\\[").replace(/[\]]/,"\\]");b=RegExp("[\\?&]"+b+"=([^&#]*)").exec(f.url);null!=b&&(a="true"==b[1]?!0:!1);return a};f.onLoadingInternalHandled=!1;f.onCompleteInternalHandled=!1;f.onLoadingInternal=function(){if(!f.onLoadingInternalHandled){if("function"==typeof f.onLoading)f.onLoading(f);f.onLoadingInternalHandled=!0}};f.evalResponse=function(){try{return eval(f.responseText||"")}catch(a){throw Error("Cannot eval the response");}};f.onCompleteInternal=function(a,b){if(!f.onCompleteInternalHandled&&
!f.aborted)if("timeout"==b)f.onTimeoutInternal();else{try{f.responseReceived=!0,f.status=a.status,f.statusText=b,f.responseText=a.responseText,f.responseXML=a.responseXML}catch(c){f.status=0}if("function"==typeof f.onComplete)f.onComplete(f);if("success"==b&&"function"==typeof f.onSuccess)if(f.onSuccess(f),f.onCompleteInternalHandled=!0,"function"==typeof f.callBack)f.callBack(f);else{if(f.callBack)try{eval(f.callBack)}catch(h){throw Error("Can not execute callback...");}}else if("function"==typeof f.onError)f.onError(f),
f.onCompleteInternalHandled=!1}};f.onTimeoutInternal=function(){if(!(null==f||null==f.request||f.onCompleteInternalHandled))if(f.aborted=!0,"function"==typeof f.onTimeout)f.onTimeout(f)};f.process=function(){f.request=b.ajax(f.url,{type:f.method,beforeSend:f.onLoadingInternal,complete:f.onCompleteInternal,contentType:"POST"==f.method?"application/x-www-form-urlencoded; charset=UTF-8":"text/plain;charset=UTF-8",data:f.queryString,timeout:f.timeout,cache:!1})};return f}function o(){function a(f){var c=
b("head");if(f){var d=f.portletResponses;if(d)for(var e=0;e<d.length;e++)c.find(".ExHead-"+d[e].portletId+":not(title)").remove();f.data&&b(f.data).find(".PORTLET-FRAGMENT").each(function(){c.find(".ExHead-"+this.parentNode.id.replace("EditMode-","")+":not(title)").remove()})}else{var k=b("body .PORTLET-FRAGMENT");c.find("[class^='ExHead-']:not(title)").each(function(){var a=this.className.substring(7),f=!0;k.each(function(){this.parentNode.id.replace("EditMode-","")===a&&(f=!1)});f&&b(this).remove()})}}
function e(a,b){b&&b.each(function(){a[0].appendChild(this)})}var k={to:null,executeScript:function(a){if(!(null==a||""==a)){try{eval(b("<div />").html(a).text());return}catch(c){}a=a.split(";");if(null!=a&&0<a.length)for(var d=0;d<a.length;d++)try{eval(a[d])}catch(e){alert(e+" : "+a[d]+"  -- "+d)}}},updateHtmlHead:function(c,d){if(c){a(c);var k=b("head"),g=c.markupHeadElements;if(g){if(g.titles&&0!=g.titles.length){var n=k.children("title"),i=g.titles[g.titles.length-1];n.length?n.replaceWith(i):
k[0].appendChild(i)}e(k,g.metas);e(k,g.bases);e(k,g.links);e(k,g.styles);for(var j=this,m=function(){if(g.scripts.length){var a=g.scripts.splice(0,1);e(k,b(a));a[0].src||m.apply(j)}else d.apply(j)},n=0;n<g.scripts.length;n++)if(i=g.scripts[n],i.src)void 0!==i.onreadystatechange?i.onreadystatechange=function(a){return function(){if(!a.readyState||/loaded|complete/.test(a.readyState))a.onreadystatechange=null,m.apply(j)}}(i):i.onload=function(a){return function(){a.onload=null;m.apply(j)}}(i),i.onerror=
function(a){return function(){a.onerror=null;m.apply(j)}}(i);m.apply(j)}}},updateBlocks:function(a,c){if(a){var e=null;c&&""!=c&&(e=b("#"+c));e=!e?b(document):e;b.each(a,function(){var a=e.find("#"+this.blockId);0==a.length&&alert(d.getMessage("TargetBlockNotFound",Array(this.blockId)));var c=b(this.data).find("#"+this.blockId);0==c.length&&alert(d.getMessage("BlockUpdateNotFound",Array(this.blockId)));a.html(c.html());if(this.scripts)for(a=0;a<this.scripts.length;a++)j("script_"+a+"_"+this.blockId,
this.scripts[a])})}},ajaxTimeout:function(){c.removeMasks(eXo.portal.AjaxRequest.maskLayer);eXo.portal.AjaxRequest.maskLayer=null;eXo.portal.CurrentRequest=null;window.location.reload()}};k.ajaxResponse=function(f,e){var g=this;e||(e=new n(g.responseText));var i=e.loadingScripts,m=i?i.immediateScripts:[];if(m.length)window.require(m,function(){m.length=0;k.ajaxResponse.apply(g,[f,e])});else if(e.markupHeadElements)k.updateHtmlHead(e,function(){e.markupHeadElements=null;k.ajaxResponse.apply(g,[f,e])});
else{(i=e.portletResponses)&&b.each(i,function(){var a=this;a.blocksToUpdate?k.updateBlocks(a.blocksToUpdate,a.portletId):(b("#"+a.portletId),b("#"+a.portletId+" .PORTLET-FRAGMENT").first().html(a.portletData),a.scripts&&a.scripts.each(function(b){j("script_"+b+"_"+a.portletId,this)}))});!e.blocksToUpdate&&""!==f.responseText&&confirm(d.getMessage("SessionTimeout"))&&k.ajaxTimeout(f);try{k.updateBlocks(e.blocksToUpdate),a(),k.executeScript(e.script),clearTimeout(k.to),c.removeMasks(eXo.portal.AjaxRequest.maskLayer),
eXo.portal.AjaxRequest.maskLayer=null,eXo.portal.CurrentRequest=null}catch(l){alert(l.message)}}};k.ajaxLoading=function(a){if(!a.isAsynchronize()){if(null==eXo.portal.AjaxRequest.maskLayer)eXo.portal.AjaxRequest.maskLayer=c.createTransparentMask();k.to=setTimeout(function(){null!=eXo.portal.AjaxRequest.maskLayer&&c.showAjaxLoading(eXo.portal.AjaxRequest.maskLayer)},2E3)}};return k}window.doRequest=function(a,b,c,d){request=new p(a,b,c);handler=new o;request.onSuccess=handler.ajaxResponse;request.onLoading=
handler.ajaxLoading;request.onTimeout=handler.ajaxTimeout;request.callBack=d;eXo.portal.CurrentRequest=request;request.process();eXo.session.startItv()};window.ajaxAbort=function(){c.removeMasks(eXo.portal.AjaxRequest.maskLayer);eXo.portal.AjaxRequest.maskLayer=null;eXo.portal.CurrentRequest.request.abort();eXo.portal.CurrentRequest.aborted=!0;eXo.portal.CurrentRequest=null};window.ajaxAsyncGetRequest=function(a,b){return ajaxRequest("GET",a,b)};window.ajaxRequest=function(a,c,d,f){void 0==d&&(d=
!0);var e;b.ajax(c,{type:a,async:d,data:f,headers:{"Cache-Control":"max-age=86400"},complete:function(a){e=a.responseText}});eXo.session.startItv();if(!d)return e};window.ajaxRedirect=function(a){a=a.replace(/&amp;/g,"&");window.location.href=a};eXo.portal.AjaxRequest=p.prototype.constructor}(i,b,g,a)});
define("SHARED/uiMaskWorkspace",["SHARED/uiMaskLayer","SHARED/base"],function(i,g){eXo.define.names=["uiMaskLayer","base"];eXo.define.deps=[i,g];return function(a,b){eXo.portal.UIMaskWorkspace={show:function(h,e){if(this.maskWorkpace=document.getElementById(h)){if(-1<e)this.maskWorkpace.style.width=e+"px";if(null==eXo.portal.UIMaskWorkspace.maskLayer){var c=b.createMask("UIPortalApplication",this.maskWorkpace,30);eXo.portal.UIMaskWorkspace.maskLayer=c}this.maskWorkpace.style.margin="auto";this.maskWorkpace.style.display=
"block";c=a.Browser;c.addOnResizeCallback("mid_maskWorkspace",eXo.portal.UIMaskWorkspace.resetPositionEvt);c.addOnScrollCallback("setPosition_maskWorkspace",eXo.portal.UIMaskWorkspace.resetPositionEvt)}},hide:function(a){this.maskWorkpace=document.getElementById(a);if(void 0!=eXo.portal.UIMaskWorkspace.maskLayer&&this.maskWorkpace)b.removeMask(eXo.portal.UIMaskWorkspace.maskLayer),eXo.portal.UIMaskWorkspace.maskLayer=null,this.maskWorkpace.style.display="none"},resetPositionEvt:function(){var a=eXo.portal.UIMaskWorkspace.maskWorkpace;
if(a&&"block"==a.style.display)try{b.blockContainer=document.getElementById("UIPortalApplication"),b.object=a,b.setPosition()}catch(e){}}};return eXo.portal.UIMaskWorkspace}(g,i)});
define("SHARED/popupCategory",["SHARED/jquery"],function(i){eXo.define.names=["$"];eXo.define.deps=[i];return function(g){eXo.webui.UIPopupSelectCategory={init:function(a){var b=a;"string"==typeof b&&(b=g("#"+a));g(b).find(".UIPopupCategory").closest(".ControlIcon, .EditIcon").off("click").on("click",function(a){eXo.webui.UIPopupSelectCategory.show(this,a)});return!1},show:function(a){var b=g(a).find("div.UIPopupCategory");b.length&&"none"==b.css("display")&&(b.show(),g(document).one("click",function(){g(document).one("click",
function(){b.hide()})}))}};return eXo.webui.UIPopupSelectCategory}(i)});
define("SHARED/uiMaskLayer",["SHARED/jquery","SHARED/base","SHARED/uiPopup"],function(i,g,a){eXo.define.names=["$","base","uiPopup"];eXo.define.deps=[i,g,a];return function(a,h,e){eXo.core.UIMaskLayer={createTransparentMask:function(c){var d=h.Browser,e=a("#AjaxLoadingMask"),c=a(eXo.core.UIMaskLayer.createMask("UIPortalApplication",e[0],0,c));d.addOnScrollCallback("5439383",eXo.core.UIMaskLayer.setPosition);e.hide();c.fadeTo(0,0);c.css("backgroundColor","white");c.css("cursor","wait");return c[0]},
showAjaxLoading:function(){document.getElementById("AjaxLoadingMask").style.display="block"},removeTransparentMask:function(){var c=a("#TransparentMaskLayer");c.length&&(c.height(0),c.width(0))},removeMasks:function(a){eXo.core.UIMaskLayer.removeTransparentMask();eXo.core.UIMaskLayer.removeMask(a)},createMask:function(c,d,k,g){try{var i=h.Browser;"string"==typeof c&&(c=a("#"+c));var l=a(c),j=a(document.createElement("div"));this.object=d;this.blockContainer=l[0];this.position=g;var p=document.getElementById("MaskLayer");
if(p)p.id="subMaskLayer";l.append(j);j.addClass("MaskLayer").attr("id","MaskLayer");j.data("maxZIndex",e.zIndex+1);var o=j.offsetParent(),r=o.offset();o.length&&0!=r.left&&0!=o.top?(j.width(o[0].offsetWidth),j.height(o[0].offsetHeight)):(j.width(a(window).width()),j.height(a(window).height()));j.css("top","0px");j.css("left","0px");j.css("zIndex",j.data("maxZIndex"));k&&j.fadeTo(0,k/100);if(null!=d){var q=document.createElement("span");d.nextSibling?d.parentNode.insertBefore(q,d.nextSibling):d.parentNode.appendChild(q);
j.data("nextSiblingOfObject",q);d.style.zIndex=j.data("maxZIndex");d.style.display="block";l.append(d);eXo.core.UIMaskLayer.setPosition();if(eXo.core.I18n.isLT()&&(l[0].offsetWidth>d.offsetLeft+d.offsetWidth&&"TOP-RIGHT"==g||"BOTTOM-RIGHT"==g))d.style.left=l[0].offsetWidth-d.offsetWidth+"px";eXo.core.UIMaskLayer.doScroll()}"UIPage"==j[0].parentNode.id&&eXo.core.UIMaskLayer.enablePageDesktop(!1)}catch(s){alert(s)}i.addOnResizeCallback(j[0].id,eXo.core.UIMaskLayer.resizeMaskLayer);return j[0]},createMaskForFrame:function(c,
d,e){try{var g=h.Browser;"string"==typeof c&&(c=a("#"+c));var i=a(c),l=a(document.createElement("div"));i.append(l);l.addClass("MaskLayer");l.attr("id",d.id+"MaskLayer");l.data("maxZIndex",3);l.width(i[0].offsetWidth);l.height(i[0].offsetHeight);window.setTimeout(function(){var c=i[0].parentNode,d;do d=c,c=c.parentNode;while(c&&"static"===a(d).css("position"));l.css("top",g.findPosYInContainer(i[0],d)+"px");l.css("left",g.findPosXInContainer(i[0],d)+"px")},200);l.css("zIndex",l.data("maxZIndex"));
e&&l.fadeTo(0,e/100);if(null!=d){var j=document.createElement("span");d.nextSibling?d.parentNode.insertBefore(j,d.nextSibling):d.parentNode.appendChild(j);l.data("nextSiblingOfObject",j);d.style.zIndex=l.data("maxZIndex")+1;d.style.display="block";i.append(d)}}catch(p){}return l[0]},doScroll:function(){var c=document.getElementById("MaskLayer");if(c){var d=c.offsetParent,e=a(d).offset();if(d&&0!=e.left||0!=e.top)if(c=document.getElementById("subMaskLayer"),!c)return;c.style.top=document.documentElement&&
document.documentElement.scrollTop?document.documentElement.scrollTop+"px":document.body.scrollTop+"px";setTimeout(function(){eXo.core.UIMaskLayer.doScroll()},1)}else if(document.getElementById("subMaskLayer"))document.getElementById("subMaskLayer").id="MaskLayer",eXo.core.UIMaskLayer.doScroll()},setPosition:function(){var c=eXo.core.UIMaskLayer,d=c.object,e=c.blockContainer,h=c.position;d.style.position="absolute";var c=document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:
document.body.scrollTop,g=a(window).height();switch(h){case "TOP-LEFT":h=c;e=0;break;case "TOP-RIGHT":h=c;e=e.offsetWidth-d.offsetWidth;break;case "TOP-CENTER":h=c;e=(e.offsetWidth-d.offsetWidth)/2;break;case "BOTTOM-LEFT":e=0;h=g-d.offsetHeight+c;break;case "BOTTOM-CENTER":e=(e.offsetWidth-d.offsetWidth)/2;h=g-d.offsetHeight+c;break;case "BOTTOM-RIGHT":e=e.offsetWidth-d.offsetWidth;h=g-d.offsetHeight+c;break;default:e=(e.offsetWidth-d.offsetWidth)/2,h=(g-d.offsetHeight)/2+c}h+d.offsetHeight>c+a(window).height()&&
(h=c+g-d.offsetHeight);d.style.left=e+"px";d.style.top=h+"px"},removeMask:function(c){if(c){c.nextSibling.style.display="none";var d=a(c).data("nextSiblingOfObject");d.parentNode.insertBefore(c.nextSibling,d);d.parentNode.removeChild(d);a(c).remove()}},enablePageDesktop:function(a){var b=document.getElementById("UIPageDesktop");if(b)b.style.zIndex=a?"":"-1"},resizeMaskLayer:function(){var c=document.getElementById("MaskLayer");if(c){var d=c.offsetParent;if(d){var e=a(d).offset();if(0!=e.top||0!=e.left){c=
document.getElementById("subMaskLayer");if(!c)return;d=c.offsetParent}}}var h=a(window);if(c&&d&&(e=a(d).offset(),0==e.left&&0==e.top))c.style.width=h.width()+"px",c.style.height=h.height()+"px"}};return eXo.core.UIMaskLayer}(i,g,a)});
define("SHARED/I18NMessage",[],function(){eXo.define.names=[];eXo.define.deps=[];return function(){eXo.i18n.I18NMessage={getMessage:function(i,g){var a;try{a=eval("this."+i)}catch(b){}if(null==a||"undefined"==a)a=i;if(null!=g&&0<g.constructor.toString().indexOf("Array"))for(var h=0;h<g.length;h++)a=a.replace("{"+h+"}",g[h]);return a},SessionTimeout:"Session timeout. Please refresh your browser.",TargetBlockNotFound:"The target block ID to update is not found : {0}",BlockUpdateNotFound:"The block ID to update is not found : {0}",
DefaultTheme:"Default Theme",PreviousMonth:"Previous Month",NextMonth:"Next Month",PreviousYear:"Previous Year",NextYear:"Next Year",weekdays:"S,M,T,W,T,F,S".split(","),Save:"Save",Cancel:"Cancel"};return eXo.i18n.I18NMessage}()});
define("SHARED/base",["SHARED/jquery"],function(i){eXo.define.names=["$"];eXo.define.deps=[i];return function(g){eXo.portal.logout=function(){window.location=eXo.env.server.createPortalURL("UIPortal","Logout",!1)};eXo.session.openUrl=null;eXo.session.itvTime=null;eXo.session.itvObj=null;eXo.session.initialized=!1;eXo.session.itvInit=function(){var a=eXo.session,b=eXo.env;if(!a.initialized&&a.canKeepState&&"private"==b.portal.accessMode){if(!a.openUrl)a.openUrl=b.server.createPortalURL("UIPortal",
"Ping",!1);if(!a.itvTime)a.itvTime=1800;a.initialized=!0;a.openItv()}};eXo.session.startItv=function(){var a=eXo.session;if(a.initialized){if(a.destroyItv(),a.canKeepState&&"private"==eXo.env.portal.accessMode&&0<a.itvTime)a.itvObj=window.setTimeout("eXo.session.openItv()",1E3*(a.itvTime-10))}else a.isOpen&&a.itvInit()};eXo.session.openItv=function(){var a=eXo.session,b=window.ActiveXObject?new ActiveXObject("Msxml2.XMLHTTP"):new XMLHttpRequest;b.open("GET",a.openUrl,!0);b.setRequestHeader("Cache-Control",
"max-age=86400");b.onreadystatechange=function(){if(4==b.readyState){if(200==b.status){var h=b.responseText;if(!isNaN(h))a.itvTime=parseInt(h)}delete b.onreadystatechange}};b.send(null)};eXo.session.destroyItv=function(){var a=eXo.session;window.clearTimeout(a.itvObj);a.itvObj=null};eXo.generateId=function(a){return a+"-"+(new Date).getTime()+Math.random().toString().substring(2)};eXo.debug=function(a){if(eXo.developing){var b=eXo.webui;b.UINotification&&b.UINotification.addMessage("DEBUG: "+a)}};
eXo.core.I18n={init:function(){var a=document.getElementsByTagName("html")[0],b=a.getAttribute("xml:lang")||a.getAttribute("lang")||"en",a=a.getAttribute("dir")||"lt";this.lang=b;this.dir=a;this.orientation="rtl"==a?"rt":"lt";this.lt="lt"==this.orientation},getLanguage:function(){return this.lang},getOrientation:function(){return this.orientation},getDir:function(){return!this.lt},isLT:function(){return this.lt},isRT:function(){return!this.lt}};eXo.core.I18n.init();eXo.core.Browser={onLoadCallback:{},
onResizeCallback:{},onScrollCallback:{},breakStream:null,init:function(){window.onresize=this.managerResize;window.onscroll=this.onScroll;this.detectBrowser()},detectBrowser:function(){this.webkit=this.gecko=this.opera=this.ie=0;this.mobile=null;this.air=0;var a=navigator.userAgent,b;if(/KHTML/.test(a))this.webkit=1;if((b=a.match(/AppleWebKit\/([^\s]*)/))&&b[1]){this.webkit=parseFloat(b[1]);if(/ Mobile\//.test(a))this.mobile="Apple";else if(b=a.match(/NokiaN[^\/]*/))this.mobile=b[0];if(b=a.match(/AdobeAIR\/([^\s]*)/))this.air=
b[0]}if(!this.webkit)if((b=a.match(/Opera[\s\/]([^\s]*)/))&&b[1]){if(this.opera=parseFloat(b[1]),b=a.match(/Opera Mini[^;]*/))this.mobile=b[0]}else if((b=a.match(/MSIE\s([^;]*)/))&&b[1])this.ie=parseFloat(b[1]);else if(b=a.match(/Gecko\/([^\s]*)/))if(this.gecko=1,(b=a.match(/rv:([^\s\)]*)/))&&b[1])this.gecko=parseFloat(b[1])},managerResize:function(){var a=eXo.core.Browser,b=g(window);if(a.currheight!=b.height())clearTimeout(a.breakStream),a.breakStream=setTimeout(a.onResize,100);a.currheight=b.height()},
isIE:function(){return 0<=navigator.userAgent.indexOf("MSIE")},isIE6:function(){return 0<=navigator.userAgent.indexOf("MSIE 6")},isIE7:function(){return 0<=navigator.userAgent.indexOf("MSIE 7")},isFF:function(){return this.gecko},isFF3:function(){return 0<=navigator.userAgent.indexOf("Firefox/3")},addOnLoadCallback:function(a,b){this.onLoadCallback[a]=b},onLoad:function(){var a=eXo.core.Browser.onLoadCallback,b;for(b in a){var h=a[b];if("function"==typeof h)try{h()}catch(e){}}this.onLoadCallback=
{}},addOnResizeCallback:function(a,b){this.onResizeCallback[a]=b},onResize:function(a){var b=eXo.core.Browser.onResizeCallback,h;for(h in b){var e=b[h];"function"==typeof e&&e(a)}},addOnScrollCallback:function(a,b){this.onScrollCallback[a]=b},onScroll:function(a){var b=eXo.core.Browser.onScrollCallback,h;for(h in b){var e=b[h];try{"function"==typeof e&&e(a)}catch(c){}}},findPosX:function(a,b){var h=g(a).offset().left;return b?h+a.offsetWidth:h},findPosXInContainer:function(a,b,h){var e=eXo.core.Browser,
a=e.findPosX(a,h),b=e.findPosX(b,h);return h?-(a-b):a-b},findPosYInContainer:function(a,b){var h=g(a).offset().top,e=g(b).offset().top;return h-e},findMouseRelativeX:function(a,b,h){a=eXo.core.Browser.findPosX(a,h);if(!b)b=window.event;b=g.event.fix(b);b=b.pageX;return-1==b?-1:b-a},findMouseRelativeY:function(a,b){var h=g(a).offset().top;if(!b)b=window.event;var b=g.event.fix(b),e=b.pageY;return-1==e?-1:e-h},setPositionInContainer:function(a,b,h,e){var c=b.offsetLeft,d=b.offsetTop,g=eXo.core.Browser,
i=g.findPosXInContainer(b,a),a=g.findPosYInContainer(b,a);b.style.left=h-(i-c)+"px";b.style.top=e-(a-d)+"px"},setCookie:function(a,b,h){var e=new Date;e.setDate(e.getDate()+h);document.cookie=a+"="+escape(b)+(null==h?"":";expires="+e.toGMTString())},getCookie:function(a){if(0<document.cookie.length){var b=document.cookie.indexOf(a+"=");if(-1!=b){b=b+a.length+1;a=document.cookie.indexOf(";",b);if(-1==a)a=document.cookie.length;return unescape(document.cookie.substring(b,a))}}return""},isDesktop:function(){return document.getElementById("UIPageDesktop")?
!0:!1},getHeightOfFreeSpace:function(){for(var a=document.body.children,b=0,h=a.length,e=0;e<h;e++)b+=a[e].offsetHeight;return g(window).height()-b},fillUpFreeSpace:function(a){"string"==typeof a&&(a=document.getElementById(a));var b=eXo.core.Browser.getHeightOfFreeSpace();if(0<b&&void 0!=a)b+=a.offsetHeight,a.style.height=b+"px";for(var h=g(document),e=g(a),a=h.height();h.height()==a;)e.height(e.height()+1);for(b=e.height()-1;h.height()>a;)e.height(e.height()-1);window.setTimeout(function(){e.height(b)},
100)}};eXo.core.Browser.init();return{Browser:eXo.core.Browser,I18n:eXo.core.I18n}}(i)});define("SHARED/skin",[],function(){eXo.define.names=[];eXo.define.deps=[];return function(){eXo.core.Skin={addSkin:function(i,g){if(null==document.getElementById(i)){var a=document.createElement("link");a.setAttribute("id",i);a.setAttribute("rel","stylesheet");a.setAttribute("type","text/css");a.setAttribute("href",g);document.getElementsByTagName("head")[0].appendChild(a)}}};return eXo.core.Skin}()});
define("SHARED/uiPopup",["SHARED/base","SHARED/jquery"],function(i,g){eXo.define.names=["base","$"];eXo.define.deps=[i,g];return function(a,b){eXo.webui.UIPopup={zIndex:3,init:function(a,b){"string"==typeof a&&(a=document.getElementById(a));if(b)a.containerId=b;a.onmousedown=this.changezIndex},changezIndex:function(){this.style.zIndex=++eXo.webui.UIPopup.zIndex},create:function(){var a=document.createElement("div");with(a.style)position="relative",display="none";return a},setSize:function(a,b,c){a.style.width=
b+"px";a.style.height=c+"px"},show:function(b){"string"==typeof b&&(b=document.getElementById(b));var e=document.getElementById("UIMaskWorkspace");if(e&&(uiMaskWSzIndex=a(e).css("zIndex"))&&uiMaskWSzIndex>eXo.webui.UIPopup.zIndex)eXo.webui.UIPopup.zIndex=uiMaskWSzIndex;b.style.zIndex=++eXo.webui.UIPopup.zIndex;b.style.display="block"},hide:function(a){"string"==typeof a&&(a=document.getElementById(a));a.style.display="none"},setPosition:function(a,b,c,d){if(a.containerId)document.getElementById(a.containerId).style.position=
"relative";a.style.position="absolute";a.style.top=c+"px";d?(a.style.right=b+"px",a.style.left=""):(a.style.left=b+"px",a.style.right="")},setAlign:function(h,e,c,d){"string"==typeof h&&(h=document.getElementById(h));var g=a(window).width()-b.Browser.findPosX(document.getElementById("UIWorkingWorkspace")),i=0,m=0;c||(c=0);d||(d=0);i=a(window).height();switch(e){case 1:i=d;m=c;break;case 2:i=d;m=g-h.offsetWidth-c;break;case 3:i=i-h.offsetHeight-d;m=c;break;case 4:i=i-h.offsetHeight-d;m=g-h.offsetWidth-
c;break;default:i=(i-h.offsetHeight)/2,m=(uiWorkingWS.offsetWidth-h.offsetWidth)/2}this.setPosition(h,m,i,eXo.core.I18n.isRT())},initDND:function(){var b=eXo.core.DragDrop,e=a(this).parent().closest(".UIDragObject")[0];b.init(this,e)}};return eXo.webui.UIPopup}(g,i)});