var eXo={core:{},env:{portal:{},client:{},server:{}},portal:{},webui:{},gadget:{},session:{},i18n:{}};window.ajaxGet=function(f,e){e||(e=null);require(["SHARED/portalRequest"],function(){doRequest("Get",f,null,e)})};window.ajaxPost=function(f,e,n){n||(n=null);require(["SHARED/portalRequest"],function(){doRequest("POST",f,e,n)})};
eXo.env.server.createPortalURL=function(f,e,n,h){f=eXo.env.server.portalURLTemplate.replace("_portal:componentId_",f);f=f.replace("_portal:action_",e);if(null!=h)for(var e=h.length,s=0;s<e;s++)var w=encodeURIComponent(h[s].name),t=encodeURIComponent(h[s].value),f=f+("&"+w+"="+t);n&&(f+="&ajaxRequest=true");return f};eXo.env.addLoadedRemoteScripts=function(f){if("function"===typeof define&&define.amd)for(var e=0;e<f.length;e++)define(f[e])};
eXo.require=function(){if(1==arguments.length){var f=eXo.define.deps,e=eXo.inArray(eXo.define.names,arguments[0]);return-1!==e?f[e]:window.require(arguments[0])}return eXo.define.apply(this,arguments)};eXo.require.config=require.config;eXo.require.undef=require.undef;eXo.require.toUrl=require.toUrl;
eXo.define=function(){var f=[],e=null;if(1==arguments.length)e=arguments[0],e instanceof Function&&(f=["require","exports","module"]);else for(var n=0;n<arguments.length;n++){var h=arguments[n];h instanceof Array?f=h:h instanceof Function&&(e=h)}for(var s=eXo.define.names,w=eXo.define.deps,h=[],n=0;n<f.length;n++){var t=eXo.inArray(s,f[n]);h[n]=-1!==t?w[t]:null}if(e instanceof Function&&(e=e.apply(this,h),!e))if(t=eXo.inArray(f,"module"),-1!==t)e=h[t].exports;else if(-1!=(t=eXo.inArray(f,"exports")))e=
h[t];return e};eXo.inArray=function(f,e){if(!f)return-1;for(var n=0;n<f.length;n++)if(f[n]===e)return n;return-1};var requirejs,require,define;
(function(f){function e(b){return"[object Function]"===K.call(b)}function n(b){return"[object Array]"===K.call(b)}function h(b,d){if(b){var i;for(i=0;i<b.length&&!d(b[i],i,b);i+=1);}}function s(b,d){if(b){var i;for(i=b.length-1;-1<i&&!d(b[i],i,b);i-=1);}}function w(b,d){for(var i in b)if(b.hasOwnProperty(i)&&d(b[i],i))break}function t(b,d,i){d&&w(d,function(d,g){if(i||!b.hasOwnProperty(g))b[g]=d})}function x(b,d){return function(){return d.apply(b,arguments)}}function $(b){if(!b)return b;var d=f;
h(b.split("."),function(b){d=d[b]});return d}function aa(b,d,i){return function(){var f=fa.call(arguments,0),g;if(i&&e(g=f[f.length-1]))g.__requireJsBuild=!0;f.push(d);return b.apply(null,f)}}function ba(b,d,i){h([["toUrl"],["undef"],["defined","requireDefined"],["specified","requireSpecified"]],function(e){b[e[0]]=aa(d[e[1]||e[0]],i)})}function I(b,d,i,e){d=Error(d+"\nhttp://requirejs.org/docs/errors.html#"+b);d.requireType=b;d.requireModules=e;if(i)d.originalError=i;return d}function ga(){if(J&&
"interactive"===J.readyState)return J;s(document.getElementsByTagName("script"),function(b){if("interactive"===b.readyState)return J=b});return J}var ha=/(\/\*([\s\S]*?)\*\/|([^:]|^)\/\/(.*)$)/mg,ia=/require\s*\(\s*["']([^'"\s]+)["']\s*\)/g,ca=/\.js$/,ja=/^\.\//,K=Object.prototype.toString,y=Array.prototype,fa=y.slice,ka=y.splice,z=!!("undefined"!==typeof window&&navigator&&document),da=!z&&"undefined"!==typeof importScripts,la=z&&"PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/,
U="undefined"!==typeof opera&&"[object Opera]"===opera.toString(),B={},u={},P=[],L=!1,p,A,E,C,F,J,G,M,N;if("undefined"===typeof define){if("undefined"!==typeof requirejs){if(e(requirejs))return;u=requirejs;requirejs=void 0}"undefined"!==typeof require&&!e(require)&&(u=require,require=void 0);p=requirejs=function(b,d,e,f){var g="_",h;!n(b)&&"string"!==typeof b&&(h=b,n(d)?(b=d,d=e,e=f):b=[]);if(h&&h.context)g=h.context;(f=B[g])||(f=B[g]=p.s.newContext(g));h&&f.configure(h);return f.require(b,d,e)};
p.config=function(b){return p(b)};require||(require=p);p.version="2.0.1";p.jsExtRegExp=/^\/|:|\?|\.js$/;p.isBrowser=z;y=p.s={contexts:B,newContext:function(b){function d(a,c,j){var v=c&&c.split("/"),b=o.map,m=b&&b["*"],k,d,e,f;if(a&&"."===a.charAt(0))if(c){v=o.pkgs[c]?[c]:v.slice(0,v.length-1);c=a=v.concat(a.split("/"));for(k=0;c[k];k+=1)if(d=c[k],"."===d)c.splice(k,1),k-=1;else if(".."===d)if(1===k&&(".."===c[2]||".."===c[0]))break;else 0<k&&(c.splice(k-1,2),k-=2);k=o.pkgs[c=a[0]];a=a.join("/");
k&&a===c+"/"+k.main&&(a=c)}else 0===a.indexOf("./")&&(a=a.substring(2));if(j&&(v||m)&&b){c=a.split("/");for(k=c.length;0<k;k-=1){e=c.slice(0,k).join("/");if(v)for(d=v.length;0<d;d-=1)if(j=b[v.slice(0,d).join("/")])if(j=j[e]){f=j;break}!f&&m&&m[e]&&(f=m[e]);if(f){c.splice(0,k,f);a=c.join("/");break}}}return a}function i(a){z&&h(document.getElementsByTagName("script"),function(c){if(c.getAttribute("data-requiremodule")===a&&c.getAttribute("data-requirecontext")===l.contextName)return c.parentNode.removeChild(c),
!0})}function T(a){var c=o.paths[a];if(c&&n(c)&&1<c.length)return i(a),c.shift(),l.undef(a),l.require([a]),!0}function g(a,c,j,v){var b=a?a.indexOf("!"):-1,m=null,k=c?c.name:null,e=a,f=!0,g="",i,h;a||(f=!1,a="_@r"+(M+=1));-1!==b&&(m=a.substring(0,b),a=a.substring(b+1,a.length));m&&(m=d(m,k,v),h=r[m]);a&&(m?g=h&&h.normalize?h.normalize(a,function(a){return d(a,k,v)}):d(a,k,v):(g=d(a,k,v),i=Q[g],i||(i=l.nameToUrl(a,null,c),Q[g]=i)));a=m&&!h&&!j?"_unnormalized"+(N+=1):"";return{prefix:m,name:g,parentMap:c,
unnormalized:!!a,url:i,originalName:e,isDefine:f,id:(m?m+"!"+g:g)+a}}function s(a){var c=a.id,j=q[c];j||(j=q[c]=new l.Module(a));return j}function u(a,c,j){var b=a.id,ea=q[b];if(r.hasOwnProperty(b)&&(!ea||ea.defineEmitComplete))"defined"===c&&j(r[b]);else s(a).on(c,j)}function D(a,c){var j=a.requireModules,b=!1;if(c)c(a);else if(h(j,function(c){if(c=q[c])c.error=a,c.events.error&&(b=!0,c.emit("error",a))}),!b)p.onError(a)}function A(){P.length&&(ka.apply(H,[H.length-1,0].concat(P)),P=[])}function y(a,
c,j){a=a&&a.map;c=aa(j||l.require,a,c);ba(c,l,a);c.isBrowser=z;return c}function B(a){delete q[a];h(O,function(c,j){if(c.map.id===a)return O.splice(j,1),c.defined||(l.waitCount-=1),!0})}function C(a,c){var j=a.map.id,b=a.depMaps,d;if(a.inited){if(c[j])return a;c[j]=!0;h(b,function(a){if(a=q[a.id])return!a.inited||!a.enabled?(d=null,delete c[j],!0):d=C(a,c)});return d}}function E(a,c,j){var b=a.map.id,d=a.depMaps;if(a.inited&&a.map.isDefine){if(c[b])return r[b];c[b]=a;h(d,function(d){var d=d.id,k=
q[d];!R[d]&&k&&(!k.inited||!k.enabled?j[b]=!0:(k=E(k,c,j),j[d]||a.defineDepById(d,k)))});a.check(!0);return r[b]}}function F(a){a.check()}function G(){var a=1E3*o.waitSeconds,c=a&&l.startTime+a<(new Date).getTime(),j=[],b=!1,d=!0,m,k,e;if(!V){V=!0;w(q,function(a){m=a.map;k=m.id;if(a.enabled&&!a.error)if(!a.inited&&c)T(k)?b=e=!0:(j.push(k),i(k));else if(!a.inited&&a.fetched&&m.isDefine&&(b=!0,!m.prefix))return d=!1});if(c&&j.length)return a=I("timeout","Load timeout for modules: "+j,null,j),a.contextName=
l.contextName,D(a);d&&(h(O,function(a){if(!a.defined){var a=C(a,{}),c={};a&&(E(a,c,{}),w(c,F))}}),w(q,F));if((!c||e)&&b)if((z||da)&&!W)W=setTimeout(function(){W=0;G()},50);V=!1}}function X(a){s(g(a[0],null,!0)).init(a[1],a[2])}function K(a){var a=a.currentTarget||a.srcElement,c=l.onScriptLoad;a.detachEvent&&!U?a.detachEvent("onreadystatechange",c):a.removeEventListener("load",c,!1);c=l.onScriptError;a.detachEvent&&!U||a.removeEventListener("error",c,!1);return{node:a,id:a&&a.getAttribute("data-requiremodule")}}
var o={waitSeconds:7,baseUrl:"./",paths:{},pkgs:{},shim:{}},q={},Y={},H=[],r={},Q={},S={},M=1,N=1,O=[],V,Z,l,R,W;R={require:function(a){return y(a)},exports:function(a){a.usingExports=!0;if(a.map.isDefine)return a.exports=r[a.map.id]={}},module:function(a){return a.module={id:a.map.id,uri:a.map.url,config:function(){return o.config&&o.config[a.map.id]||{}},exports:r[a.map.id]}}};Z=function(a){this.events=Y[a.id]||{};this.map=a;this.shim=o.shim[a.id];this.depExports=[];this.depMaps=[];this.depMatched=
[];this.pluginMaps={};this.depCount=0};Z.prototype={init:function(a,c,b,d){d=d||{};if(!this.inited){this.factory=c;if(b)this.on("error",b);else this.events.error&&(b=x(this,function(a){this.emit("error",a)}));h(a,x(this,function(a,c){"string"===typeof a&&(a=g(a,this.map.isDefine?this.map:this.map.parentMap,!1,!0),this.depMaps.push(a));var d=R[a.id];d?this.depExports[c]=d(this):(this.depCount+=1,u(a,"defined",x(this,function(a){this.defineDep(c,a);this.check()})),b&&u(a,"error",b))}));this.inited=
!0;this.ignore=d.ignore;d.enabled||this.enabled?this.enable():this.check()}},defineDepById:function(a,c){var b;h(this.depMaps,function(c,d){if(c.id===a)return b=d,!0});return this.defineDep(b,c)},defineDep:function(a,c){this.depMatched[a]||(this.depMatched[a]=!0,this.depCount-=1,this.depExports[a]=c)},fetch:function(){if(!this.fetched)this.fetched=!0,l.startTime=(new Date).getTime(),this.map.prefix?this.callPlugin():this.shim?y(this,!0)(this.shim.deps||[],x(this,function(){this.load()})):this.load()},
load:function(){var a=this.map.url;S[a]||(S[a]=!0,l.load(this.map.id,a))},check:function(a){if(this.enabled){var c=this.map.id,b=this.depExports,d=this.exports,f=this.factory,m;if(this.inited)if(this.error)this.emit("error",this.error);else{if(!this.defining){this.defining=!0;if(1>this.depCount&&!this.defined){if(e(f)){if(this.events.error)try{d=l.execCb(c,f,b,d)}catch(k){m=k}else d=l.execCb(c,f,b,d);if(this.map.isDefine)if((b=this.module)&&void 0!==b.exports&&b.exports!==this.exports)d=b.exports;
else if(void 0===d&&this.usingExports)d=this.exports;if(m)return m.requireMap=this.map,m.requireModules=[this.map.id],m.requireType="define",D(this.error=m)}else d=f;this.exports=d;if(this.map.isDefine&&!this.ignore&&(r[c]=d,p.onResourceLoad))p.onResourceLoad(l,this.map,this.depMaps);delete q[c];this.defined=!0;l.waitCount-=1;0===l.waitCount&&(O=[])}this.defining=!1;if(!a&&this.defined&&!this.defineEmitted)this.defineEmitted=!0,this.emit("defined",this.exports),this.defineEmitComplete=!0}}else this.fetch()}},
callPlugin:function(){var a=this.map,c=a.id,b=g(a.prefix,null,!1,!0);u(b,"defined",x(this,function(b){var j=this.map.name,e=this.map.parentMap?this.map.parentMap.name:null;if(this.map.unnormalized){if(b.normalize&&(j=b.normalize(j,function(a){return d(a,e,!0)})||""),b=g(a.prefix+"!"+j),u(b,"defined",x(this,function(a){this.init([],function(){return a},null,{enabled:!0,ignore:!0})})),b=q[b.id]){if(this.events.error)b.on("error",x(this,function(a){this.emit("error",a)}));b.enable()}}else j=x(this,function(a){this.init([],
function(){return a},null,{enabled:!0})}),j.error=x(this,function(a){this.inited=!0;this.error=a;a.requireModules=[c];w(q,function(a){0===a.map.id.indexOf(c+"_unnormalized")&&B(a.map.id)});D(a)}),j.fromText=function(a,c){var b=L;b&&(L=!1);p.exec(c);b&&(L=!0);l.completeLoad(a)},b.load(a.name,y(a.parentMap,!0,function(a,c){return l.require(a,c)}),j,o)}));l.enable(b,this);this.pluginMaps[b.id]=b},enable:function(){this.enabled=!0;if(!this.waitPushed)O.push(this),l.waitCount+=1,this.waitPushed=!0;h(this.depMaps,
x(this,function(a){var c=a.id,b=q[c];!R[c]&&b&&!b.enabled&&l.enable(a,this)}));w(this.pluginMaps,x(this,function(a){var c=q[a.id];c&&!c.enabled&&l.enable(a,this)}));this.check()},on:function(a,c){var b=this.events[a];b||(b=this.events[a]=[]);b.push(c)},emit:function(a,c){h(this.events[a],function(a){a(c)});"error"===a&&delete this.events[a]}};return l={config:o,contextName:b,registry:q,defined:r,urlMap:Q,urlFetched:S,waitCount:0,defQueue:H,Module:Z,makeModuleMap:g,configure:function(a){a.baseUrl&&
"/"!==a.baseUrl.charAt(a.baseUrl.length-1)&&(a.baseUrl+="/");var c=o.paths,b=o.pkgs,d=o.shim,e=o.map||{};t(o,a,!0);t(c,a.paths,!0);o.paths=c;if(a.map)t(e,a.map,!0),o.map=e;if(a.shim)w(a.shim,function(a,c){n(a)&&(a={deps:a});if(a.exports&&!a.exports.__buildReady)a.exports=l.makeShimExports(a.exports);d[c]=a}),o.shim=d;if(a.packages)h(a.packages,function(a){a="string"===typeof a?{name:a}:a;b[a.name]={name:a.name,location:a.location||a.name,main:(a.main||"main").replace(ja,"").replace(ca,"")}}),o.pkgs=
b;if(a.deps||a.callback)l.require(a.deps||[],a.callback)},makeShimExports:function(a){var c;return"string"===typeof a?(c=function(){return $(a)},c.exports=a,c):function(){return a.apply(f,arguments)}},requireDefined:function(a,c){var b=g(a,c,!1,!0).id;return r.hasOwnProperty(b)},requireSpecified:function(a,c){a=g(a,c,!1,!0).id;return r.hasOwnProperty(a)||q.hasOwnProperty(a)},require:function(a,c,d,f){var i;if("string"===typeof a){if(e(c))return D(I("requireargs","Invalid require call"),d);if(p.get)return p.get(l,
a,c);a=g(a,c,!1,!0);a=a.id;return!r.hasOwnProperty(a)?D(I("notloaded",'Module name "'+a+'" has not been loaded yet for context: '+b)):r[a]}d&&!e(d)&&(f=d,d=void 0);c&&!e(c)&&(f=c,c=void 0);for(A();H.length;){i=H.shift();if(null===i[0])return D(I("mismatch","Mismatched anonymous define() module: "+i[i.length-1]));X(i)}s(g(null,f)).init(a,c,d,{enabled:!0});G();return l.require},undef:function(a){var c=g(a,null,!0),b=q[a];delete r[a];delete Q[a];delete S[c.url];delete Y[a];if(b){if(b.events.defined)Y[a]=
b.events;B(a)}},enable:function(a){q[a.id]&&s(a).enable()},completeLoad:function(a){var c=o.shim[a]||{},b=c.exports&&c.exports.exports,d,e;for(A();H.length;){e=H.shift();if(null===e[0]){e[0]=a;if(d)break;d=!0}else e[0]===a&&(d=!0);X(e)}e=q[a];if(!d&&!r[a]&&e&&!e.inited){if(o.enforceDefine&&(!b||!$(b)))return T(a)?void 0:D(I("nodefine","No define call for "+a,null,[a]));X([a,c.deps||[],c.exports])}G()},toUrl:function(a,c){var b=a.lastIndexOf("."),d=null;-1!==b&&(d=a.substring(b,a.length),a=a.substring(0,
b));return l.nameToUrl(a,d,c)},nameToUrl:function(a,c,b){var e,f,i,g,h,a=d(a,b&&b.id,!0);if(p.jsExtRegExp.test(a))c=a+(c||"");else{e=o.paths;f=o.pkgs;b=a.split("/");for(g=b.length;0<g;g-=1)if(h=b.slice(0,g).join("/"),i=f[h],h=e[h]){n(h)&&(h=h[0]);b.splice(0,g,h);break}else if(i){a=a===i.name?i.location+"/"+i.main:i.location;b.splice(0,g,a);break}c=b.join("/")+(c||".js");c=("/"===c.charAt(0)||c.match(/^[\w\+\.\-]+:/)?"":o.baseUrl)+c}return o.urlArgs?c+((-1===c.indexOf("?")?"?":"&")+o.urlArgs):c},load:function(a,
b){p.load(l,a,b)},execCb:function(a,b,d,e){return b.apply(e,d)},onScriptLoad:function(a){if("load"===a.type||la.test((a.currentTarget||a.srcElement).readyState))J=null,a=K(a),l.completeLoad(a.id)},onScriptError:function(a){var b=K(a);if(!T(b.id))return D(I("scripterror","Script error",a,[b.id]))}}}};p({});ba(p,B._);if(z&&(A=y.head=document.getElementsByTagName("head")[0],E=document.getElementsByTagName("base")[0]))A=y.head=E.parentNode;p.onError=function(b){throw b;};p.load=function(b,d,e){var f=
b&&b.config||{},g;if(z)return g=f.xhtml?document.createElementNS("http://www.w3.org/1999/xhtml","html:script"):document.createElement("script"),g.type=f.scriptType||"text/javascript",g.charset="utf-8",g.setAttribute("data-requirecontext",b.contextName),g.setAttribute("data-requiremodule",d),g.attachEvent&&!(g.attachEvent.toString&&0>g.attachEvent.toString().indexOf("[native code"))&&!U?(L=!0,g.attachEvent("onreadystatechange",b.onScriptLoad)):(g.addEventListener("load",b.onScriptLoad,!1),g.addEventListener("error",
b.onScriptError,!1)),g.src=e,G=g,E?A.insertBefore(g,E):A.appendChild(g),G=null,g;da&&(importScripts(e),b.completeLoad(d))};z&&s(document.getElementsByTagName("script"),function(b){if(!A)A=b.parentNode;if(C=b.getAttribute("data-main")){if(!u.baseUrl)F=C.split("/"),M=F.pop(),N=F.length?F.join("/")+"/":"./",u.baseUrl=N,C=M.replace(ca,"");u.deps=u.deps?u.deps.concat(C):[C];return!0}});define=function(b,d,f){var h,g;"string"!==typeof b&&(f=d,d=b,b=null);n(d)||(f=d,d=[]);!d.length&&e(f)&&f.length&&(f.toString().replace(ha,
"").replace(ia,function(b,e){d.push(e)}),d=(1===f.length?["require"]:["require","exports","module"]).concat(d));if(L&&(h=G||ga()))b||(b=h.getAttribute("data-requiremodule")),g=B[h.getAttribute("data-requirecontext")];(g?g.defQueue:P).push([b,d,f])};define.amd={jQuery:!0};p.exec=function(b){return eval(b)};p(u)}})(this);"function"===typeof define&&define.amd&&!require.specified("SHARED/bootstrap")&&define("SHARED/bootstrap");