define("SHARED/portalDragDrop",["SHARED/base","SHARED/jquery","SHARED/common"],function(l,m,o){eXo.define.names=["base","$","common"];eXo.define.deps=[l,m,o];return function(h,f,r){eXo.portal.PortalDragDrop={init:function(a){if(a&&a.length){h(".UIPageBody").find(".DragControlArea, .uiIconDragDrop").off("mouseover").on("mouseover",function(){this.style.cursor=1==eXo.portal.portalMode||2==eXo.portal.portalMode?"move":"default"});var d=f.Browser,b=r.DragDrop,c=eXo.portal.PortalDragDrop,e=null,j=function(a,
g,k,p,q){if(!eXo.portal.isInDragging){var f=this,k=h(this),r={},p=["top",eXo.core.I18n.isLT()?"left":"right","zIndex","opacity","filter","position","width"];h.each(p,function(c,e){r[e]=f.style[e]});k.data("origDragObjectStyle",r);p=0==k.children(".UIComponentBlock").length;!p&&d.isIE7()&&(a=d.findPosXInContainer(f,h("#UIWorkingWorkspace")[0]));k.data("backupParentSibling",k.parent().next("td"));var l=f.offsetWidth;if(p){var m=k.clone(!0,!0);k.before(m);b.init(m[0],m[0]);m[0].onDragStart=j;m[0].onDrag=
s;m[0].onDragEnd=n;k.width(l);k.fadeTo(0,0.5)}else e=c.createPreview(),f.parentNode.insertBefore(e,f),k.width(300).find(".EDITION-BLOCK .NewLayer").each(function(){h(this).width(300)});f.isAddingNewly=p;f.style.position="absolute";f.style.top=g+"px";g=a;q=d.findMouseRelativeX(f.offsetParent,q)-a;150<q&&(g=a+q-300*q/l);f.style.left=eXo.core.I18n.isRT()&&!p&&!k.hasClass("UIPageBody")?a+l-300+"px":g+"px";k.data("dropableTargets",c.findDropableTargets(f));eXo.portal.isInDragging=!0}},s=function(b,g,a,
d,j){var f=this,b=h(this);eXo.portal.PortalDragDrop.scrollOnDrag(f,j);if(g=c.findTarget(f,a,d)||b.data("lastFoundTargetObject")){b.data("lastFoundTargetObject",b.data("foundTargetObject"));b.data("foundTargetObject",g);j=h(g);"UIPage"==g.className?g=j.find(".VIEW-PAGE").first():"UIPortal"==g.className?g=eXo.portal.portalMode%2?j.find(".LAYOUT-PORTAL").first():j.find(".VIEW-PORTAL").first():(g=h(g),g=eXo.portal.portalMode%2?g.find(".LAYOUT-BLOCK").first():g.find(".VIEW-BLOCK").first(),g.css("height",
"auto"));g=g.children("div").first().children("div");g=0==g.length?null:g[0];c.layoutTypeElementNode=g;null==e&&(e=c.createPreview());if(null!=g&&!h(g).hasClass("UITableColumnContainer")){a=j.find(".UIRowContainer").first();j=a.children("div").filter(function(){return"DragAndDropPreview"!=this.className&&this!=f});b.data("listComponentInTarget",j);d=eXo.portal.PortalDragDrop.findInsertPosition(j,"row",d);if(b.data("foundTargetObject")===b.data("lastFoundTargetObject")&&d===b.data("foundIndex"))return;
b.data("foundIndex",d);0<=d?a[0].insertBefore(e,j[d]):a[0].appendChild(e)}else{g=j.find(".TRContainer").first();j=g.children("td").filter(function(){return this!=e.parentNode&&this!=f.parentNode});d=eXo.portal.PortalDragDrop.findInsertPosition(j,"column",a);if(b.data("foundTargetObject")===b.data("lastFoundTargetObject")&&d===b.data("foundIndex"))return;b.data("foundIndex",d);0<=d?g[0].insertBefore(f.parentNode,j[d]):g[0].appendChild(f.parentNode)}a=h(f).parent();1==a.children("div").length&&!a.hasClass("EmptyContainer")&&
a.addClass("EmptyContainer")}},n=function(c,b,a,j,d){c=!0;b=h(this);27===d.which&&(c=!1);b.data("foundTargetObject")||b.data("foundTargetObject",b.data("lastFoundTargetObject"));a=b.data("foundTargetObject");j=b.data("foundIndex");if(!a||void 0==j)c=!1;if(!this.isAddingNewly)if("td"==this.parentNode.tagName.toLowerCase()){if(a=b.data("backupParentSibling"),j=b.parent().next("td"),0==a.length&&0==j.length||j[0]==a[0])c=!1}else if(a=b.next("div.DragAndDropPreview"),j=b.prev("div.DragAndDropPreview"),
a.length||j.length)c=!1;this.isAddingNewly||(b.find(".EDITION-BLOCK").last().hide(),h.extend(this.style,b.data("origDragObjectStyle")));if(27!==d.which)eXo.portal.PortalDragDrop.doDropCallback(this);else{if(this.parentNode&&"td"==this.parentNode.tagName.toLowerCase())d=this.parentNode,a=b.data("backupParentSibling"),0==a.length?d.parentNode.appendChild(d):d.parentNode.insertBefore(d,a[0]);this.isAddingNewly&&this.parentNode.removeChild(this)}e&&e.parentNode.removeChild(e);e=null;eXo.portal.isInDragging=
!1;c&&window.require(["SHARED/portalComposer"],function(b){b.toggleSaveButton()});b.removeData()},a=a.join(",.");h("."+a).each(function(){var c=h(this).find(".DragControlArea, .uiIconDragDrop").last(),c=0!=c.length?c[0]:this;b.init(c,this);this.onDragStart=j;this.onDrag=s;this.onDragEnd=n})}},doDropCallback:function(a){var d=h(a),b=eXo.portal.PortalDragDrop,c=d.data("foundTargetObject"),e=d.data("foundIndex");!c||void 0==e?a.isAddingNewly?a.parentNode.removeChild(a):a.parentNode.replaceChild(a,a):
(!a.isAddingNewly&&void 0!=e&&null!=b.layoutTypeElementNode&&eXo.portal.PortalDragDrop.divRowContainerAddChild(a,c,e),a.isAddingNewly&&d.remove(),a=[{name:"srcID",value:a.id.replace(/^UIPortlet-/,"")},{name:"targetID",value:c.id.replace(/^.*-/,"")},{name:"insertPosition",value:e},{name:"isAddingNewly",value:a.isAddingNewly}],ajaxGet(eXo.env.server.createPortalURL("UIPortal","MoveChild",!0,a)))},findDropableTargets:function(a){var d=[],b=h(a);if(b.hasClass("UIColumnContainer"))return a=b.closest(".UITableColumnContainer"),
d.push(a[0]),d;var a=h("#UIPortalToolPanel"),c=a.find(".UIPortal");c.length||(c=a.find(".UIPage"));d.push(c[0]);a.find(".UIContainer").each(function(){var c=h(this);!c.closest(b).length&&!c.hasClass("ProtectedContainer")&&!c.hasClass("UITableColumnContainer")&&d.push(this)});return d},scrollOnDrag:function(a,d){var b=h(window),c=h("#UIWorkingWorkspace").height(),e=b.height();if(!(c<=e)){var j=d.clientY,c=j-Math.round(5*e/6),e=j-Math.round(e/6),j=b.scrollTop();0<c&&b.scrollTop(j+c-5);0>e&&0<j&&b.scrollTop(j+
e)}},findInsertPosition:function(a,d,b){var c=f.Browser;if("row"==d)for(d=0;d<a.length;d++){var e=h(a[d]).offset().top,c=b,e=e+Math.round(a[d].offsetHeight/2);if(!(c>e))return d}else for(d=0;d<a.length;d++){var e=b,j=c.findPosX(a[d],eXo.core.I18n.isRT());if(eXo.core.I18n.isRT()){if(e<j)continue}else if(e>j)continue;return d}return-1},createPreview:function(){var a=document.createElement("div");a.className="DragAndDropPreview";a.id="DragAndDropPreview";return a},findTarget:function(a,d,b){var c=h(a).data("dropableTargets");
if(!c)return null;for(var e=null,j=c.length,f=0;f<j;f++){var n=c[f];a!=n&&this.isIn(d,b,n)&&(null==e?e=n:0<h(n).closest(e).length&&(e=n))}return e},isIn:function(a,d,b){var c=h(b).offset(),e=c.left,j=e+b.offsetWidth,c=c.top,b=c+b.offsetHeight,f=!1;e<a&&a<j&&c<d&&d<b&&(f=!0);return f},divRowContainerAddChild:function(a,d,b){var c=h(a).data("listComponentInTarget"),d=h(d).find(".UIRowContainer").first(),e=a.parentNode;0<=b?d[0].insertBefore(a,c[b]):d[0].appendChild(a);d.removeClass("EmptyContainer");
"td"==e.nodeName.toLowerCase()&&h(e).remove()}};return eXo.portal.PortalDragDrop}(m,l,o)});
define("SHARED/portalComposer",["SHARED/portalControl","SHARED/portalDragDrop","SHARED/jquery","SHARED/portalRequest","SHARED/bts_tooltip"],function(l,m,o,h,f){eXo.define.names=["portalControl","portalDragDrop","$","portalRequest","bts_tooltip"];eXo.define.deps=[l,m,o,h,f];return function(f,a,d){var b={init:function(c,e,a,d,h){eXo.portal.portalMode=h;eXo.portal.hasEditted=d;f("div#"+c).attr("exo:minWidth",e).attr("exo:minHeight",a).find(".uiIconArrowRightMini, .uiIconArrowDownMini").on("click",function(){b.toggle(f(this))});
f("div#"+c).find('[rel="tooltip"]').tooltip()},initComposerContent:function(c,e){b.showTab(e);f("#"+c).find(".MiddleTab, .nav-tabs a").each(function(c){f(this).on("click",function(){var e=f(this);e.closest(".nav-tabs").length?(e.tab("show"),e=f(this).next("input")):e=f(this).children("input");b.showTab(e.attr("name"));f.globalEval(e.attr("value"));eXo.portal.portalMode&&(eXo.portal.portalMode+=2*(0==c?-1:1))})})},toggle:function(c){var b=c.closest(".uiPortalComposer"),a=b.children(".popupContent").eq(0);
"block"==a.css("display")?(a.hide(),a.next(".uiAction").hide(),b.children("span:first").removeClass("uiIconResize"),c.attr("class","uiIconArrowRightMini pull-left")):(a.show(),a.next(".uiAction").show(),b.children("span:first").addClass("uiIconResize"),c.attr("class","uiIconArrowDownMini pull-left"));ajaxAsyncGetRequest(eXo.env.server.createPortalURL(b.attr("id"),"Toggle",!0))},showTab:function(c){var b=f("#UIPortalToolPanel");"UIApplicationList"==c?(b.attr("class","ApplicationMode"),d.init(["UIPageBody"])):
"UIContainerList"==c&&(b.attr("class","ContainerMode"),f("#UIPageBody").find(".DragControlArea, .uiIconDragDrop").off("mousedown"))},toggleSaveButton:function(){if(!eXo.portal.hasEditted){eXo.portal.hasEditted=!0;var b=f("#UIWorkingWorkspace").find(".uiPortalComposer").eq(0);b.find(".uiIconSave.uiIconLightGray").removeClass("uiIconLightGray").addClass("uiIconDarkGray");ajaxAsyncGetRequest(eXo.env.server.createPortalURL(b.attr("id"),"ChangeEdittedState",!0))}}};return b}(o,l,m)});
define("SHARED/portal",["SHARED/base","SHARED/jquery","SHARED/I18NMessage","SHARED/bts_tooltip"],function(l,m,o,h){eXo.define.names=["base","$","msg","bts_tooltip"];eXo.define.deps=[l,m,o,h];return function(f,h,a){var d={initForm:function(){f(".uiFormInputThemeSelector").find(".setDefault").on("click",function(){d.setDefaultTheme(this,"DefaultTheme")})},initSelector:function(){f(".uiFormInputThemeSelector").find(".uiThemeSelector").parent().on("click",function(){var b=f(this).children("div").attr("class").replace("uiThemeSelector ",
"");d.showThemeSelected(this,b)})},showThemeSelected:function(b,c){var e=f(b),a=e.parent().closest(".itemListContainer").next("div").find(".uiThemeSelector").eq(0);a.next("div").html(e.find(".nameStyle").eq(0).html());a.attr("class","uiThemeSelector "+c);e.parent().parent().children("input").eq(0).val(c)},setDefaultTheme:function(b,c){var e=f(b).parent().closest(".itemDetailList"),d=e.find(".uiThemeSelector").eq(0);d.attr("class","uiThemeSelector "+c);d.next("div").html(a.getMessage("DefaultTheme"));
e.prev("div").find("div.itemList").eq(0).parent().children("input").eq(0).val(c)}};eXo.webui.UIPageTemplateOptions={selectPageLayout:function(b,c){var e=f("#"+b),a=e.closest(".itemListContainer"),d=a.find(".itemList"),a=a.find(".OptionItem"),e=e.closest(".uiItemSelector").find(".itemDetailList");if(0!=d.length)for(i=0;i<a.length;++i)if(!(i>=d.length))if(i==c){if(d[i].style.display="block",!(1>e.length)){e[i].style.display="block";var h=f(d[i]).find(".selectedItem").eq(0);h&&null!=h&&(h=h.find("#SetValue")[0],
null!=h&&eval(h.innerHTML))}}else if(d[i].style.display="none",0<e.length)e[i].style.display="none"}};eXo.portal.UIPortal={portalUIComponentDragDrop:!1,initMouseHover:function(b){b=f("#"+b);b.length&&(b.mouseenter(function(b){eXo.portal.UIPortal.blockOnMouseOver(b,this,!0)}),b.mouseleave(function(b){eXo.portal.UIPortal.blockOnMouseOver(b,this,!1)}))},blockOnMouseOver:function(b,c,a){c=f(c);if(!(!eXo.portal.portalMode||eXo.portal.isInDragging||2>=eXo.portal.portalMode&&c.hasClass("UIContainer"))&&
!(2<eXo.portal.portalMode&&4!=eXo.portal.portalMode&&c.hasClass("UIPortlet"))){if(!b)b=window.event;b.cancelBubble=!0;var d,m,n;c.find("div.UIComponentBlock").eq(0).children("div").each(function(){var b=f(this);b.hasClass("VIEW-BLOCK")?d=b:b.hasClass("LAYOUT-BLOCK")?m=b:b.hasClass("EDITION-BLOCK")&&(n=b)});if(n){c.hasClass("UIPortlet")&&c.find(".portletLayoutDecorator, .portletLayoutDecoratorHover").toggleClass("portletLayoutDecorator portletLayoutDecoratorHover");if(a){var a=n.find("div.NewLayer").eq(0),
l=0,g=0,k=n.parents("div.UIContainer:last");eXo.portal.UIPortal.blockOnMouseOver(b,k,!1);k.find("div.UIContainer").each(function(){eXo.portal.UIPortal.blockOnMouseOver(b,this,!1)});if(m&&"none"!=m.css("display"))l=m[0].offsetHeight,g=m[0].offsetWidth;else if(d&&"none"!=d.css("display"))l=d[0].offsetHeight,g=d[0].offsetWidth;c.hasClass("UIPortlet")?(a.css("width",g+"px"),a.css("height",l+"px")):(a.parent().css("width",g+"px"),g=c.children("div.NormalContainerBlock"),0<g.length&&g.eq(0).removeClass("NormalContainerBlock").addClass("OverContainerBlock"));
n.css("display","block");0!=f(m,d).find("div > .UIRowContainer > .uiTabContainer").length?(a.parent().css("top",-l-5+"px"),a.next(".CONTROL-BLOCK").height(17)):a.parent().css("top",-l+"px");if((a=n.find("div.UIInfoBar, .uiInfoBar").eq(0))&&(h.Browser.isIE6()||h.Browser.isIE7()&&eXo.core.I18n.isRT())&&""==a.css("width"))c.hasClass("UIPortlet")?(c=a.find("div.PortletIcon"),l=a.find("a.EditPortletPropertiesIcon"),g=a.find("a.DeletePortletIcon")):(c=a.find("div.ContainerIcon"),l=a.find("a.EditContainerIcon"),
g=a.find("a.DeleteContainerIcon")),k=a.find(".DragControlArea, .uiIconDragDrop")[0].offsetWidth,k+=c[0].offsetWidth,0<l.length&&(k+=l[0].offsetWidth),0<g.length&&(k+=g[0].offsetWidth),a.css("width",k+35+"px");a.find('[rel="tooltip"]').tooltip()}else n.css("display","none"),c.hasClass("UIContainer")&&(g=c.find("div.OverContainerBlock"),0<g.length&&(g.eq(0).removeClass("OverContainerBlock").addClass("NormalContainerBlock"),c.hasClass("UIPortlet")||eXo.portal.UIPortal.blockOnMouseOver(b,c.closest("div.UIComponentBlock").parent(),
!0)));c=n.find("div.CONTROL-PORTLET");0<c.length&&c.eq(0).css("display",4==eXo.portal.portalMode?"none":"block")}}},showLayoutModeForPage:function(){var b=f(document.body).find("div.UIPage");0!=b.length&&(b=b.find("div.VIEW-PAGE").eq(0),"Vista"!=f("#UIPortalApplication").attr("class")&&b.css("border","solid 3px #dadada"),0<b.find("div.UIContainer,div.UIPortlet").length?b.css({border:"none",paddingTop:"5px",paddingRight:"5px",paddingBottom:"5px",paddingLeft:"5px"}):b.css({paddingTop:"50px",paddingRight:"0px",
paddingBottom:"50px",paddingLeft:"0px"}))},showViewMode:function(){var b=f("#UIWorkingWorkspace");0==b.find("div.UIPortlet").length&&0==b.find("div.UIContainer").length&&f("#UIPage").parents(".VIEW-PAGE").css({paddingTop:"50px",paddingRight:"0px",paddingBottom:"50px",paddingLeft:"0px"});var b=f("#UIPageBody"),a=b.find("div.UIPageBodyMask");0<a.length&&a.css("top",-b[0].offsetHeight+"px").css("height",b[0].offsetHeight+"px").css("width",b[0].offsetWidth+"px")},changePortal:function(b,a){window.location=
eXo.env.server.context+"/"+b+"/"+a+"/"},popupButton:function(b,a){void 0==a&&(a="");window.location=b+"&action="+a},removeComponent:function(b){var a=f("#"+b),d=a.parent(),b=d.closest(".VIEW-PAGE");"TD"==d[0].nodeName.toUpperCase()?d.remove():a.remove();a=f("#UIWorkingWorkspace");0<b.length&&0==a.find("div.UIContainer").length&&0==a.find("div.UIPortlet").length&&b.css({paddingTop:"50px",paddingRight:"0px",paddingBottom:"50px",paddingLeft:"0px"})}};return{UIPortal:eXo.portal.UIPortal,UIPageTemplateOptions:eXo.webui.UIPageTemplateOptions,
UIFormInputThemeSelector:d}}(m,l,o)});