define("SHARED/socialUtil",["SHARED/jquery","SHARED/uiMaskLayer","SHARED/uiPopupWindow"],function(h,i,k){eXo.define.names=["gj","uiMaskLayer","popupWindow"];eXo.define.deps=[h,i,k];return function(f,e,h,i){if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};f.social=f.social||{};if(f.env){var g=f.env.portal;f.social.portal={rest:g.rest?g.rest:"rest-socialdemo",portalName:g.portalName?g.portalName:"classic",context:g.context?g.context:"/socialdemo",accessMode:g.accessMode?
g.accessMode:"public",userName:g.userName?g.userName:""}}f.social.I18n=f.social.I18n||{};f.social.I18n.mentions=f.social.I18n.mentions||{helpSearch:"Type to start searching for users.",searching:"Searching for ",foundNoMatch:"Found no matching users for "};var j={ADDED_MARGIN_BOTTOM:10,dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",
identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera"},{string:navigator.vendor,subString:"iCab",identity:"iCab"},{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,
subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],adjustHeight:function(a){var b=this.getCurrentBrowser();null!=b?"Safari"==b||"Chrome"==b?gadgets.window.adjustHeight(a.offsetHeight+this.ADDED_MARGIN_BOTTOM):gadgets.window.adjustHeight():gadgets.window.adjustHeight()},applyConfirmPopup:function(a){e("#"+a).find(".confirmPopup").on("click",function(){var a=e(this),c=a.attr("data-onclick"),d=a.attr("data-labelAction")||
"OK",g=a.attr("data-labelClose")||"Close",h=a.attr("data-title")||"Confirmation",a=a.attr("data-message");f.social.PopupConfirmation.confirm("demo",[{action:c,label:d}],h,a,g)})},feedbackMessagePopup:function(a,b,c){var d=PopupConfirmation.makeTemplate();d.find(".popupTitle").html(a);b=b.replace("${simpleQuote}","'");d.find(".contentMessage").removeClass("confirmationIcon").addClass("infoIcon").html(b);d.find(".uiAction").append(PopupConfirmation.addAction(null,c));PopupConfirmation.show(d)},feedbackMessageInline:function(a,
b){var b=b.replace("${simpleQuote}","'"),c=e("#feedbackmessageInline");0===c.length&&(c=e('<div id="feedbackMessageInline" class="alert alert-success">  <i class="uiIconSuccess"></i><span class="message"></span></div>'),c.prependTo(e("#"+a)));e(window).scrollTop()>c.offset().top&&c[0].scrollIntoView(!0);c.stop().hide().find("span.message").text(b);c.show("fast").delay(4500).hide("slow")},getCurrentBrowser:function(){return function(a){for(var b=0;b<a.length;b++){var c=a[b].string,d=a[b].prop;this.versionSearchString=
a[b].versionSearch||a[b].identity;if(c){if(-1!=c.indexOf(a[b].subString))return a[b].identity}else if(d)return a[b].identity}}(this.dataBrowser)||null},setCookies:function(a,b,c){var d=new Date;d.setDate(d.getDate()+c);c=null==c?"":";expires="+d.toGMTString();document.cookie=a+"="+escape(b)+c+";path=/portal"}};PopupConfirmation={actions:[],title:"",message:"",makeTemplate:function(){e("#UISocialPopupConfirmation").remove();var a=e(".UISocialConfirmation:first").clone();a.attr("id","UISocialPopupConfirmation");
a.find(".uiIconClose:first").on("click",PopupConfirmation.hiden);return a},confirm:function(a,b,c,d,e){j.setCookies("currentConfirm",a,300);a=PopupConfirmation.makeTemplate();a.find(".popupTitle").html(c);a.find(".contentMessage").html(d);c=a.find(".uiAction");for(d=0;d<b.length;++d)c.append(PopupConfirmation.addAction(b[d].action,b[d].label));c.append(PopupConfirmation.addAction(null,e));PopupConfirmation.show(a)},addAction:function(a,b){var c=e('<a href="javascript:void(0);" class="btn">'+b+"</a>");
c.on("click",PopupConfirmation.hiden);"function"===typeof a?(c.on("mouseup",a),c.html(b)):null!==a&&c.attr("onclick",a);return c},show:function(a){e("#UIPortalApplication").append(a);a.css({height:"auto",width:"400px",visibility:"hidden",display:"block"});var b=a.height(),c=(e(window).height()-b)/2-30,c=(10<c?c:10)+e(window).scrollTop(),d=(e(window).width()-a.width())/2;a.css({top:c+"px",left:d+"px",visibility:"visible",overflow:"hidden"});a.animate({height:b+"px"},500,function(){});h.createMask(a[0].parentNode,
a[0],1);i.initDND(a.find(".popupTitle")[0],a[0])},hiden:function(){var a=e(this).parents("#UISocialPopupConfirmation");0<a.length&&(h.removeMask(a[0].previousSibling),a.animate({height:"0px"},300,function(){e(this).remove()}));j.setCookies("currentConfirm","",-300)},executeCurrentConfirm:function(){var a=f.core.Browser.getCookie("currentConfirm");if(a&&0<(""+a).length){var b=e("#"+a);0<b.length&&("SocialCurrentConfirm"===a&&b.removeAttr("id"),b.trigger("click"))}}};setTimeout(PopupConfirmation.executeCurrentConfirm,
220);f.social.PopupConfirmation=f.social.PopupConfirmation||PopupConfirmation;j.PopupConfirmation=f.social.PopupConfirmation;return f.social.SocialUtil=j}(window.eXo,h,i,k)});