define("SHARED/userPopupPlugin",["SHARED/jquery"],function(i){eXo.define.names=["jQuery"];eXo.define.deps=[i];return function(a){a.fn.userPopup=function(i){var c=a.extend({restURL:"",labels:"",getContentFunc:function(){},activation:"hover",keepAlive:!1,maxWidth:"200px",edgeOffset:3,defaultPosition:"bottom",delay:400,fadeIn:200,fadeOut:200,attribute:"title",content:!1,enter:function(){},exit:function(){}},i);if(0>=a("#tiptip_holder").length){var j=a('<div id="tiptip_holder" style="max-width:'+c.maxWidth+
';"></div>'),p=a('<div id="tiptip_content"></div>'),u=a('<div id="tiptip_arrow"></div>');a("body").append(j.html(p).prepend(u.html('<div id="tiptip_arrow_inner"></div>')))}else j=a("#tiptip_holder"),p=a("#tiptip_content"),u=a("#tiptip_arrow");return this.each(function(){var k=a(this);if(""!=(c.content?c.content:k.attr(c.attribute))){c.content||k.removeAttr(c.attribute);var q=!1;"hover"==c.activation?(k.hover(function(){w(a(this));clearTimeout(a(this).data("timeoutId"));i()},function(){c.keepAlive||
l();var b=a(this),d=setTimeout(function(){j.is(":hover")||l()},250);b.data("timeoutId",d)}),c.keepAlive&&j.hover(function(){},function(){l()})):"focus"==c.activation?k.focus(function(){i()}).blur(function(){l()}):"click"==c.activation&&(k.click(function(){i();return!1}).hover(function(){},function(){c.keepAlive||l()}),c.keepAlive&&j.hover(function(){},function(){l()}));var i=function(){c.enter.call(this);j.hide().removeAttr("class").css("margin","0");u.removeAttr("style");var b=parseInt(k.offset().top),
d=parseInt(k.offset().left),e=parseInt(k.outerWidth()),n=parseInt(k.outerHeight()),m=j.outerWidth(),g=j.outerHeight(),o=Math.round((e-m)/2),i=Math.round((n-g)/2),r=Math.round(d+o),h=Math.round(b+n+c.edgeOffset),f="",s="",l=Math.round(m-12)/2;"bottom"==c.defaultPosition?f="_bottom":"top"==c.defaultPosition?f="_top":"left"==c.defaultPosition?f="_left":"right"==c.defaultPosition&&(f="_right");var p=o+d<parseInt(a(window).scrollLeft()),t=m+d>parseInt(a(window).width());if(p&&0>o||"_right"==f&&!t||"_left"==
f&&d<m+c.edgeOffset+5)f="_right",s=Math.round(g-13)/2,l=-12,r=Math.round(d+e+c.edgeOffset),h=Math.round(b+i);else if(t&&0>o||"_left"==f&&!p)f="_left",s=Math.round(g-13)/2,l=Math.round(m),r=Math.round(d-(m+c.edgeOffset+5)),h=Math.round(b+i);d=b+n+c.edgeOffset+g+8>parseInt(a(window).height()+a(window).scrollTop());e=0>b+n-(c.edgeOffset+g+8);if(d||"_bottom"==f&&d||"_top"==f&&!e)f="_top"==f||"_bottom"==f?"_top":f+"_top",s=g,h=Math.round(b-(g+5+c.edgeOffset));else if(e|("_top"==f&&e)||"_bottom"==f&&!d)f=
"_top"==f||"_bottom"==f?"_bottom":f+"_bottom",s=-12,h=Math.round(b+n+c.edgeOffset);if("_right_top"==f||"_left_top"==f)h+=5;else if("_right_bottom"==f||"_left_bottom"==f)h-=5;if("_left_top"==f||"_left_bottom"==f)r+=5;u.css({"margin-left":l+"px","margin-top":s+"px"});j.css({"margin-left":r+"px","margin-top":h+"px"}).attr("class","tip"+f);q&&clearTimeout(q);q=setTimeout(function(){j.stop(!0,!0).fadeIn(c.fadeIn)},c.delay)},l=function(){c.exit.call(this);q&&clearTimeout(q);j.fadeOut(c.fadeOut)},w=function(b){var b=
a(b).attr("href"),d=b.substring(b.lastIndexOf("/")+1),b=c.restURL.replace("{0}",window.encodeURI(d));x();var e=y(d);e?t(e,d):a.ajax({type:"GET",url:b}).complete(function(b){if(4===b.readyState&&(b=a.parseJSON(b.responseText))){var c=d,e=a("div#socialUsersData");0==e.length&&(e=a('<div id="socialUsersData"></div>').appendTo(a(document.body)),e.hide());var c="result"+(" "===c?"_20":c),o=e.data("CacheSearch");"undefined"===""+o&&(o={});o[c]=b;e.data("CacheSearch",o);t(b,d)}})},x=function(){var b=a("<div/>",
{id:"profile-popup","class":"profile-popup",height:"100px"}),d=a("<div/>",{id:"loading-indicator"}),e=a("<div/>",{id:"loading-text",text:""+c.labels.StatusTitle});a("#tiptip_content").find("div.loading-indicator").remove();for(var n=1;9>n;n++)d.append(a('<div id="rotateG_0'+n+'" class="blockG"></div>'));b.append(d);b.append(e);p.html(b)},t=function(b,d){var e=b.relationshipType,n=eXo.social.portal.userName,m=null,g=c.labels;p.empty();n!=d&&(m=a("<div/>",{"class":"connect btn btn-primary",text:""+
g.Connect,"data-action":"Invite:"+d,onclick:"takeAction(this)"}),"pending"==e?m=a("<div/>",{"class":"connect btn btn-primary",text:""+g.Confirm,"data-action":"Accept:"+d,onclick:"takeAction(this)"}):"waiting"==e?m=a("<div/>",{"class":"connect btn",text:""+g.CancelRequest,"data-action":"Revoke:"+d,onclick:"takeAction(this)"}):"confirmed"==e?m=a("<div/>",{"class":"connect btn",text:""+g.RemoveConnection,"data-action":"Disconnect:"+d,onclick:"takeAction(this)"}):"ignored"==e&&(m=a("<div/>",{"class":"connect btn",
text:""+g.Ignore,"data-action":"Deny:"+d,onclick:"takeAction(this)"})));var e=a("<div/>"),g=a("<table/>",{id:"tipName"}),o=a("<tbody/>"),i=a("<tr/>"),j=a("<td/>",{width:"50px"}),h=a("<img/>",{src:b.avatarURL}),f=a("<a/>",{target:"_self",href:b.profileUrl});j.append(f.append(h));h=a("<td/>");f=a("<a/>",{target:"_self",href:b.profileUrl,text:b.fullName});h.append(f);b.position&&(f=a("<div/>",{"font-weight":"normal",text:b.position}),h.append(f));i.append(j).append(h);o.append(i);g.append(o);if(b.activityTitle)var k=
a("<blockquote/>",{text:b.activityTitle.replace(/<[^>]+>/g,"")});e.append(g);k&&e.append(k);if(n!=d)var l=a("<div/>",{"class":"uiAction connectAction"}).append(m);l&&e.append(l);p.html(e.html())},y=function(b){var b="result"+(" "===b?"_20":b),c=a("div#socialUsersData").data("CacheSearch");return"undefined"===""+c?null:c[b]},v=function(){a("div#socialUsersData").stop().animate({cursor:"none"},1E3,function(){a(this).data("CacheSearch",{})})};window.takeAction=function(b){var d=k.parents("div.userList:first"),
e=a(b).parents("div#tiptip_content:first").find("table#tipName:first").find("a:first").attr("href").replace("activities","profile"),d=d.find('a[href$="'+e+'"]:first').parents("div.spaceBox:first");0<d.length?(a(d).find("div.connectionBtn").find("button.btn:first").click(),a(b).closest("#tiptip_holder").fadeOut("fast"),v()):(e=a(b).attr("data-action"),d=e.split(":")[0],e=e.split(":")[1],a.ajax({type:"GET",url:c.restURL.replace("{0}",e)+"?updatedType="+d}).complete(function(c){4===c.readyState&&(a(b).closest("#tiptip_holder").fadeOut("fast",
function(){}),v())}))}}})}}(i)});