define("SHARED/uiPopupMessages",["SHARED/jquery","SHARED/uiPopupWindow","SHARED/bts_collapse"],function(h,d,a){eXo.define.names=["$","uiPopupWindow","bts_collapse"];eXo.define.deps=[h,d,a];return function(a,e){return{init:function(f){a("#"+f+" *[data-toggle='collapse']").parent().on("show hide",function(){a(this).find("i").toggleClass("uiIconArrowRight uiIconArrowDown")})},show:function(a,b){e.show(a,b)},hide:function(a,b){e.hide(a,b)}}}(h,d)});
define("SHARED/selectors",["SHARED/jquery"],function(h){eXo.define.names=["$"];eXo.define.deps=[h];return function(d){var a={init:function(b,j,c){b=d(b);c||(b.on("mouseover",function(){a.onOver(this,!0)}),b.on("mouseout",function(){a.onOver(this,!1)}));b.each(function(b){var c=d(this);c.on("click",function(){a.onClick(this);c.find(".ExtraActions, .extraActions").each(function(){var b=d(this).html();eval(b)});if(j)a.onClickCategory(this,null,j[b].componentName,j[b].categoryName)})})},onOver:function(b,
j){"Item"==b.className&&a.beforeActionHappen(b);j?(this.backupClass=b.className,b.className="OverItem Item"):b.className=this.backupClass},onClick:function(b){var j=d(b).closest(".itemListContainer, .ItemListContainer")[0],j=d(j).find("div.Item, .item").get();a.beforeActionHappen(b);if(!(0>=this.allItems.length))for(var c=0;c<j.length;c++){var f=d(j[c]);if(f[0]!=b)f.removeClass("SelectedItem selectedItem"),this.onChangeItemDetail(b,!0);else{var e="SelectedItem";this.backupClass="SelectedItem Item";
if(f.hasClass("item"))e="selectedItem",this.backupClass="selectedItem item";f.hasClass(e)||f.addClass(e);this.onChangeItemDetail(b,!1)}}},onChangeItemDetail:function(b,a){if(this.allItems&&!(0>=this.allItems.length))for(var c=a?0:0;c<this.allItems.length;c++)this.itemDetails[c].style.display=this.allItems[c]==b?"block":"none"},onClickCategory:function(b,j,c,f){a.onClick(b);if(null==a.SelectedItem)a.SelectedItem={};a.SelectedItem.component=c;a.SelectedItem.option=f},onClickOption:function(b,j,c,f){for(var j=
d(b).closest(".itemDetailList").find(".selectedItem").get(),e=0;e<j.length;e++)j[e].className="normalItem";b.className="selectedItem";if(null==a.SelectedItem)a.SelectedItem={};a.SelectedItem.component=c;a.SelectedItem.option=f},beforeActionHappen:function(b){b=d(b);this.uiItemSelector=b.closest(".UIItemSelector, .uiItemSelector")[0];var a=b.closest(".ItemListContainer, .itemListContainer");this.itemListContainer=a[0];this.itemListAray=a.parent().find("div.ItemList, .itemList").get();if(1<this.itemListAray.length){this.itemDetailLists=
d(this.uiItemSelector).find("div.ItemDetailList, .itemDetailList").get();this.itemDetailList=null;for(a=0;a<this.itemListAray.length;a++)"none"==this.itemListAray[a].style.display?this.itemDetailLists[a].style.display="none":(this.itemDetailList=this.itemDetailLists[a],this.itemDetailList.style.display="block")}else this.itemDetailList=d(this.uiItemSelector).find("div.ItemDetailList, .itemDetailList")[0];this.itemDetails=d(this.itemDetailList).find("div.ItemDetail, .itemDetail").get();this.itemList=
b.closest(".ItemList, .itemList")[0];this.allItems=d(this.itemList).find("div.Item, .item").get()},showPopupCategory:function(b){var b=d(b).closest(".ItemListContainer"),a=b.find("div.UIPopupCategory").eq(0);b.css("position","relative");"none"==a.css("display")?a.css({position:"absolute",top:"23px",left:"0px",display:"block",width:"100%"}):a.css("display","none")},selectCategory:function(b){var c=d(b),f=c.closest(".OverflowContainer"),e=a.findIndex(b),b=f.find("div.ItemList"),g=f.find("div.ItemDetailList");
b.each(function(b){b==e?(d(this).css("display","block"),g.get(b).style.display="block"):(d(this).css("display","none"),g.get(b).style.display="none")});c.closest(".UIPopupCategory").css("display","none")},findIndex:function(b){for(var a=d(b).parent().children("div."+b.className).get(),c=0;c<a.length;c++)if(a[c]==b)return c}},c={init:function(b,f){var e=c,k=d(".uiChangeLanguageForm"),g=k.find(".uiAction").find(".btn").first(),l=g.attr("href");g.on("click",function(){e.changeLanguage(l);return!1});
e.SelectedItem={component:b.component,option:b.option};k.find(".nodeLabel").closest(".selectedItem, .normalItem").each(function(b){var c=f[b];d(this).on("click",function(){a.onClickOption(this,null,c.component,c.option)})})},changeLanguage:function(b){var c="";if(void 0!=a.SelectedItem)c=a.SelectedItem.option;void 0==c&&(c="");window.location=b+"&language="+c}},e={init:function(){var b=e,a=d(".UIChangeSkinForm").find(".UIAction, .uiAction").find("a, .btn").first(),c=a.attr("href");a.on("click",function(){b.changeSkin(c);
return!1})},changeSkin:function(b){var c="";if(void 0!=a.SelectedItem)c=a.SelectedItem.option;void 0==c&&(c="");window.location=b+"&skin="+c}},f={init:function(b,a,c){"string"==typeof b&&(b=document.getElementById(b));var b=d(b),e=b.find("input.checkbox");e.each(function(b){e[b].onclick=0==b?f.checkAll:f.check});b.find(".searchByGroup input").attr("placeholder",a);b.find(".searchByUser input").attr("placeholder",c).each(function(){d(this).on("keypress",function(b){if(f.isEnterPress(b))return d.globalEval(d(this).closest(".uiSearch").find(".btnSearchUser").attr("href")),
!1})})},checkAll:function(){f.checkAllItem(this)},getItems:function(b){return d(b).parent().closest("table").find("input.checkbox").get()},check:function(){f.checkItem(this)},checkAllItem:function(b){for(var a=b.checked,b=f.getItems(b),c=b.length,e=1;e<c;e++)b[e].checked=a},checkItem:function(b){var a=f.getItems(b),c=a.length,e=!0;if(b.checked){for(b=1;b<c;b++)e=e&&a[b].checked;a[0].checked=e}else a[0].checked=!1},getKeynum:function(b){var a=!1;if(window.event)a=window.event.keyCode,b=window.event;
else if(b.which)a=b.which;if(0==a)a=b.keyCode;return a},isEnterPress:function(a){return 13==f.getKeynum(a||window.event)?!0:!1},cancelSubmit:function(){return!1}};return{UIItemSelector:a,UILanguageSelector:c,UISkinSelector:e,UIUserSelector:f}}(h)});
define("SHARED/uiForm",["SHARED/jquery","SHARED/portalRequest"],function(h,d){eXo.define.names=["$","portalRequest"];eXo.define.deps=[h,d];return function(a){eXo.webui.UIForm={ajaxPost:function(c,e){e||(e=null);var f=a(c).serialize();ajaxPost(c.action+"&ajaxRequest=true",f,e)},getFormElemt:function(c){c=c.split("#");return 1==c.length?a("#"+c[0])[0]:a("#"+c[0]).find("#"+c[1])[0]},submitForm:function(a,e,f,b){b||(b=null);a=this.getFormElemt(a);try{if(FCKeditorAPI&&"object"==typeof FCKeditorAPI)for(var d in FCKeditorAPI.__Instances){var h;
try{(h=FCKeditorAPI.__Instances[d])&&h.GetParentForm&&h.GetParentForm()==a&&h.UpdateLinkedField()}catch(k){}}}catch(g){}a.elements.formOp.value=e;f?this.ajaxPost(a,b):a.submit()},submitEvent:function(a,e,f){a=this.getFormElemt(a);try{if(FCKeditorAPI&&"object"==typeof FCKeditorAPI)for(var b in FCKeditorAPI.__Instances){var d=FCKeditorAPI.__Instances[b];d.GetParentForm&&d.GetParentForm()==a&&d.UpdateLinkedField()}}catch(h){}a.elements.formOp.value=e;if(!a.originalAction)a.originalAction=a.action;a.action=
a.originalAction+encodeURI(f);this.ajaxPost(a)},selectBoxOnChange:function(c,e){a(e).closest(".UISelectBoxOnChange").find("div.SelectBoxContentContainer").eq(0).children("div.SelectBoxContent").each(function(c){c==e.selectedIndex?a(this).css("display","block"):a(this).css("display","none")})},setHiddenValue:function(c,e,f){var b=document.getElementById(c);null==b&&(b=a("#UIMaskWorkspace").find("#"+c)[0]);b.elements[e].value=f}};return eXo.webui.UIForm}(h)});
define("SHARED/uiPopupWindow",["SHARED/common","SHARED/uiPopup","SHARED/uiMaskLayer","SHARED/base","SHARED/jquery"],function(h,d,a,c,e){eXo.define.names=["common","uiPopup","uiMaskLayer","base","$"];eXo.define.deps=[h,d,a,c,e];return function(a,b,c,e,d){var g={superClass:d,show:function(b,c,e,d){var i=document.getElementById(b);if(null!=i)this.initDND(a(i).find("span.PopupTitle")[0],i),b=a(i).find(".ResizeButton, .uiIconResize").last(),b.length&&(b.show(),b.off().on("mousedown",this.startResizeEvt)),
c&&g.showMask(i,!0),i.style.visibility="hidden",this.superClass.show(i),0<a(i).find("iframe").length?setTimeout(function(){g.setupWindow(i,e,d)},500):this.setupWindow(i,e,d)},setupWindow:function(b,c,e){var d=a(b),i=g.getResizeBlock(d);e&&i.css("max-height",e);e=a(window).height();e<d[0].offsetHeight&&(i.css("max-height",""),d=e-d[0].offsetHeight+i.height()-20,i.height(10<=d?d:10));i=0;d=b.offsetParent;i=void 0!=window.pageYOffset?window.pageYOffset:document.documentElement&&document.documentElement.scrollTop?
document.documentElement.scrollTop:document.body.scrollTop;if(d){var h=a(d).is(".UIPopupWindow,.UIWindow");if(h)b.style.top=Math.ceil((d.offsetHeight-b.offsetHeight)/2)+"px";if(c||!h)b.style.top=Math.ceil((e-b.offsetHeight)/2)+i+"px";if(a(d).hasClass("UIMaskWorkspace"))b.style.top=Math.ceil((d.offsetHeight-b.offsetHeight)/2)+"px";c=300<b.offsetHeight;if(document.getElementById("UIDockBar")&&c)b.style.top="6px";b.style.left=Math.ceil((d.offsetWidth-b.offsetWidth)/2)+"px"}if(0>a(b).offset().top)b.style.top=
i+"px";b.style.visibility="visible"},hide:function(a,b){var c=document.getElementById(a);null!=c&&(this.superClass.hide(c),b&&g.showMask(c,!1))},showMask:function(b,c){var d=b.previousSibling;d&&"MaskLayer"!=d.className&&(d=null);c?1>a(b).parents(".PORTLET-FRAGMENT").length?d||e.createMask(b.parentNode,b,1):d||e.createMaskForFrame(b.parentNode,b,1):d&&e.removeMask(d)},startResizeEvt:function(c){g.backupEvent=null;if(0<=navigator.userAgent.indexOf("MSIE")){if(!g.resizedPopup&&document.onselectstart)g.backupEvent=
document.onselectstart;document.onselectstart=function(){return!1}}else{if(document.onmousedown)g.backupEvent=document.onmousedown;document.onmousedown=function(){return!1}}var e=a(this).parents(".UIPopupWindow, .uiPopup")[0];g.resizedPopup=e;g.vresized=g.getResizeBlock(a(e));g.backupPointerY=b.Browser.findMouseRelativeY(e,c);c=a(document);c.on("mousemove.UIPopupWindow",g.resize);c.on("mouseup.UIPopupWindow",g.endResizeEvt)},resize:function(c){var e=g.resizedPopup,d=g.vresized,h=eXo.core.I18n.isRT(),
i=b.Browser.findMouseRelativeX(e,c,h),c=b.Browser.findMouseRelativeY(e,c),j=c-g.backupPointerY,k=0;d.each(function(){a(this).height()&&(k=a(this).height())});if(0<k+j)g.backupPointerY=c,d.height(k+j),d.css("max-height","");e.style.height="auto";h&&(i*=-1);if(230<i)e.style.width=i+10+"px"},endResizeEvt:function(){g.resizedPopup=null;g.vresized=null;a(document).off("mousemove.UIPopupWindow").off("mouseup.UIPopupWindow");0<=navigator.userAgent.indexOf("MSIE")?document.onselectstart=g.backupEvent:document.onmousedown=
g.backupEvent;g.backupEvent=null},initDND:function(e,d){c.DragDrop.init(e,d);d.onDragStart=function(){if(b.Browser.isFF()&&d.uiWindowContent)d.uiWindowContent.style.overflow="auto",a(d.uiWindowContent).find("ul.PopupMessageBox").css("overflow","auto")};d.onDrag=function(){};d.onDragEnd=function(c,e,g,h){if(b.Browser.isFF()&&d.uiWindowContent)d.uiWindowContent.style.overflow="auto",a(d.uiWindowContent).find("ul.PopupMessageBox").css("overflow","auto");if(c=d.offsetParent){if(0>h)d.style.top=0-c.offsetTop+
"px"}else d.style.top="0px"};d.onCancel=function(){}},getResizeBlock:function(b){var c=function(){return a(this).closest(".uiPopup").attr("id")===b.attr("id")};b.find(".resizable .resizable").filter(c).removeClass("resizable");var d=b.find(".resizable").filter(c),c=b.find("div.PopupContent, .popupContent").filter(c);return d.length?d:c}};return g}(e,c,h,a,d)});
define("SHARED/portalControl",["SHARED/uiForm","SHARED/jquery"],function(h,d){eXo.define.names=["uiForm","$"];eXo.define.deps=[h,d];return function(){eXo.portal.VerticalScrollManager={repeat:null,initScroll:function(a,c,e){var f=eXo.portal.VerticalScrollManager,a=d(a).closest(".ItemContainer").find(".MiddleItemContainer").first()[0];if(!a.id)a.id="IC"+(new Date).getTime()+Math.random().toString().substring(2);f.scrollComponent(a.id,c,e);document.onmouseup=f.cancelScroll},scrollComponent:function(a,
c,d){var f=eXo.portal.VerticalScrollManager,b=document.getElementById(a);b.scrollTop=c?b.scrollTop-d:b.scrollTop+d;f.repeat&&f.cancelScroll();f.repeat=setTimeout(function(){eXo.portal.VerticalScrollManager.scrollComponent(a,c,d)},100)},cancelScroll:function(){clearTimeout(eXo.portal.VerticalScrollManager.repeat);eXo.portal.VerticalScrollManager.repeat=null}};eXo.webui.UIHorizontalTabs={init:function(a){if(a)d("#"+a).find("div.TabsContainer").find("div.UITab").find("div.MiddleTab").not(".LockedTab").on("click",
function(){eXo.webui.UIHorizontalTabs.displayTabContent(this)})},displayTabContent:function(a){this.changeTabForUITabPane(a,null,null)},changeTabForUITabPane:function(a){var c=d(a).parents(".UITab").eq(0),e=d(a).parents(".UIHorizontalTabs"),a=e.find("div.UITab"),e=e.parent().find("div.UITabContentContainer"),f=e.children("div.UITabContent");(e=e.children("form").eq(0))&&(f=f.add("div.UITabContent",e));a.each(function(a){var e=d(this).children("div").eq(0);"DisabledTab"!=e.attr("class")&&(d(this)[0]==
c[0]?(e.removeAttr("class").attr("class","SelectedTab"),f.eq(a).css("display","block")):(e.removeAttr("class").attr("class","NormalTab"),f.eq(a).css("display","none")))})},checkContentAvailable:function(a){a=document.getElementById(a).parentNode;if(!a.isLoaded)return a.isLoaded=!0,!1;a.style.display="block";return!0},changeTabForUIFormTabpane:function(a,c,d){this.displayTabContent(a);h.setHiddenValue(c,"currentSelectedTab",d)}};return{UIPortalControl:{collapseTree:function(a){var c=d(a).parent().closest(".Node"),
a='<div onclick="'+c.find("div.ChildrenContainer").eq(0).attr("actionLink")+'" class="ExpandIcon">'+a.innerHTML+"</div>";c.html(a)},onEnterPress:function(a,c){var a=window.event||a,d;if(!a)a=window.event;if(a.keyCode)d=a.keyCode;else if(a.which)d=a.which;if(13==d)if(window.event?a.returnValue=!1:a.preventDefault(),d=document.getElementById("UIPortalLoginFormAction"))d.onclick();else c&&eval(c)},onKeyPress:function(a,c,d){if(!a)a=window.event;if(a.keyCode&&a.keyCode==d)window.event?a.cancelBubble=
!0:a.preventDefault(),c&&eval(c)}},UIHorizontalTabs:eXo.webui.UIHorizontalTabs,VerticalScrollManager:eXo.portal.VerticalScrollManager}}(d,h)});